### ISSUE TITLE
Image captions not wrapped

### ISSUE THREAD

**Issue by michalfrankl** [EHRI/ehri-nn-hugo-theme#1]
Longer image captions expand the background area, leading to an unwanted visual effect.

![ehri-nn-theme_caption_not_wrapped](https://github.com/EHRI/ehri-nn-hugo-theme/assets/526896/57467ea3-fbff-4caa-bdae-4373eea5662d)

**Comment by mikesname** [comment]
This should be fixed in 9eee731e89b48c8f85889c04dba436eb9cae861c. Note that the css class has changes as well but I've altered the CZ site accordingly.
